name: Rust

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

env:
  CARGO_TERM_COLOR: always

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        target: [aarch64-unknown-uefi, x86_64-unknown-uefi]
        type: [dev, release]

    steps:
      - uses: actions/checkout@v6

      # Format check
      - name: Install Rustfmt [FORMAT 1/2]
        run: rustup component add rustfmt
        working-directory: ./rust
      - name: Check format [FORMAT 2/2]
        run: cargo fmt -- --check
        working-directory: ./rust

      # Linting
      - name: Install Clippy [LINTING 1/2]
        run: rustup component add rustfmt
        working-directory: ./rust
        if: matrix.target == 'x86_64-unknown-uefi'
      - name: Run clippy [LINTING 2/2]
        run: cargo fmt -- --check
        working-directory: ./rust
        if: matrix.target == 'x86_64-unknown-uefi'

      # Building
      - name: Build (dev)
        run: cargo build --verbose --target ${{ matrix.target }}
        working-directory: ./rust
        if: matrix.type == 'dev'

      - name: Build (release)
        run: cargo build --verbose --release --target ${{ matrix.target }}
        working-directory: ./rust
        if: matrix.type == 'release'
